
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-6pm-2
owner: ucsb-cs156-w24
repo_name: team03-w24-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ1NTE5MDIy","is_bot":false,"login":"mbharti12","name":"Mihir B"},"headRefName":"mb-UCSBDiningCommonsMenuItem-edit-page","number":95,"title":"Mb - ucsb dining commons menu item edit page","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-2/pull/95"},{"author":{"id":"MDQ6VXNlcjQ1NTE5MDIy","is_bot":false,"login":"mbharti12","name":"Mihir B"},"headRefName":"mb-UCSBDiningCommonsMenuItem-index-page","number":94,"title":"Mb - ucsb dining commons menu item index page","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-2/pull/94"},{"author":{"id":"MDQ6VXNlcjQ1NTE5MDIy","is_bot":false,"login":"mbharti12","name":"Mihir B"},"headRefName":"mb-UCSBDiningCommonsMenuItem-create-page","number":92,"title":"Mb - ucsb dining commons menu item create page","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-2/pull/92"},{"author":{"id":"MDQ6VXNlcjQ1NTE5MDIy","is_bot":false,"login":"mbharti12","name":"Mihir B"},"headRefName":"mb-UCSBDiningCommonsMenuItem-copy-placeholders","number":90,"title":"Mb - ucsb dining commons menu item copy placeholders","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-2/pull/90"},{"author":{"id":"MDQ6VXNlcjQ1NTE5MDIy","is_bot":false,"login":"mbharti12","name":"Mihir B"},"headRefName":"mb-UCSBDiningCommonsMenuItem-table-component","number":87,"title":"Mb - ucsb dining commons menu item table component","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-2/pull/87"},{"author":{"id":"MDQ6VXNlcjQ1NTE5MDIy","is_bot":false,"login":"mbharti12","name":"Mihir B"},"headRefName":"mb-UCSBDiningCommonsMenuItem-form-component","number":85,"title":"Mb - ucsb dining commons menu item form component","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-2/pull/85"}]
