
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-6pm-2
owner: ucsb-cs156-w24
repo_name: team03-w24-6pm-2
pull_requests: [{"author":{"id":"U_kgDOB2-wIw","is_bot":false,"login":"thienanvuu","name":"Thienan Vu"},"headRefName":"Thienan-RecReq","number":67,"title":"RecommendationRequest - Create personal dokku dev deployment","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-2/pull/67"},{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"Kevin-Organization-Form","number":66,"title":"KL- completed organization form","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-2/pull/66"},{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"Kevin-Organization-Fixture","number":65,"title":"KL - Completed Fixtures and fixed issues","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-2/pull/65"},{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"Kevin-README-Table","number":64,"title":"KL - added README table","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-2/pull/64"},{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"Kevin-README-Links","number":63,"title":"KL - added links to README","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-2/pull/63"}]
